version: '3.8'

services:
  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: aitu-db
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '3N1ZXIiOiJJc3N1ZXIiLC'
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Сервис вашего Spring Boot приложения
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Если Dockerfile называется иначе, укажите нужное имя
    container_name: aitu-app

    # Переменные окружения, которые внутри контейнера будут доступны приложению
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db:5432/postgres'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: '3N1ZXIiOiJJc3N1ZXIiLC'

      # JWT-переменные. Если у вас в коде сделано чтение из application.properties,
      # можно дополнительно подключать в Spring Boot параметр --spring.config.location,
      # либо маппить ENV -> application.properties в самом приложении.
      # Ниже пример, если вы читаете secret/expiration из ENV:
      JWT_SECRET: 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTczOTg5NjI5NiwiaWF0IjoxNzM5ODk2Mjk2fQ.zEzfAatlEB1bKTxB7DjYEFoen_t33GjT9h8X-0zH0LY'
      JWT_EXPIRATION: 86400000

    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data:
